-- AlterTable
ALTER TABLE "AgentRun" ADD COLUMN     "pid" INTEGER,
ADD COLUMN     "terminalAt" TIMESTAMP(3),
ADD COLUMN     "worktreePath" TEXT;

-- AlterTable
-- `verifyCommands`/`setupCommands` are NOT NULL here, which is a deliberate departure from
-- Prisma's own generated DDL for a required String[] with no @default (which is a plain nullable
-- TEXT[]). Prisma leaves the field optional in the generated create-input type too — see
-- `verifyCommands?: ...` / `setupCommands?: ...` on `WorkspaceCreateInput` in
-- `packages/db/src/generated/models/Workspace.ts` — so nothing before the database enforces
-- this at all; the NOT NULL column is the only real check.
-- The departure is intentional: an empty verifyCommands is not a neutral default here, it is a
-- refusal to ever let a task on this workspace verify as complete (see Workspace.verifyCommands
-- in schema.prisma). A caller that forgets the field should fail loudly at creation, not silently
-- get `[]` and produce a workspace whose tasks can never complete. The two-step
-- ADD COLUMN ... DEFAULT / DROP DEFAULT sequence backfills the one existing seeded row (whose
-- verifyCommand is being dropped in the same statement, its value not carried across — harmless
-- here because the row is regenerated by the reseed that always follows this migration) without
-- leaving a lingering default for future inserts to rely on instead of supplying the value.
ALTER TABLE "Workspace" DROP COLUMN "verifyCommand",
ADD COLUMN     "haltedAt" TIMESTAMP(3),
ADD COLUMN     "haltedReason" TEXT,
ADD COLUMN     "setupCommands" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "verifyCommands" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Workspace" ALTER COLUMN "setupCommands" DROP DEFAULT;
ALTER TABLE "Workspace" ALTER COLUMN "verifyCommands" DROP DEFAULT;

-- CreateTable
CREATE TABLE "Checkpoint" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "worktreePath" TEXT NOT NULL,
    "pauseFlagPath" TEXT NOT NULL,
    "lastToolUseId" TEXT,
    "lastToolName" TEXT,
    "numTurns" INTEGER NOT NULL DEFAULT 0,
    "deniedToolUseIds" TEXT[],
    "headCommit" TEXT NOT NULL,
    "dirtyFiles" TEXT[],
    "cumulativeCostUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "cumulativeTokens" INTEGER NOT NULL DEFAULT 0,
    "pauseReason" TEXT,
    "requestedBy" TEXT,
    "ts" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Checkpoint_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Checkpoint_runId_key" ON "Checkpoint"("runId");

-- AddForeignKey
ALTER TABLE "Checkpoint" ADD CONSTRAINT "Checkpoint_runId_fkey" FOREIGN KEY ("runId") REFERENCES "AgentRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
