// Generated by Prisma. Both packages it assumes — `prisma` and `dotenv` — are declared in this
// package's devDependencies. `dotenv/config` is load-bearing, not generator residue: it is what
// puts DATABASE_URL into the environment for `db:migrate` and `db:generate`, neither of which
// passes the URL any other way.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
